version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
  backend-go:
    build: ./backend/go
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=your_jwt_secret_key
  backend-python:
    build: ./backend/python
    ports:
      - "8001:8001"
