---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-vue-front-pvc
  namespace: crolord
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: crolord-cnfs-uat-nas-tlv4v # 使用初始化配置CNFS文件系统
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-vue-front
  namespace: crolord
  labels:
    app: micro-vue-front
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: micro-vue-front
  template:
    metadata:
      labels:
        app: micro-vue-front
    spec:
      containers:
        - name: micro-vue-front
          image: crolord-uat-registry-vpc.cn-hongkong.cr.aliyuncs.com/micro/micro-front-uat:1.0.17
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo 'postStart hook executed' > /tmp/postStart.log"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "nginx -s quit; sleep 10"]
          securityContext:
            runAsUser: 0  # 以 root 用户运行
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: app-vue-front-storage
              mountPath: /usr/share/nginx/html/app-vue-front-storage
      volumes:
        - name: nginx-config
          configMap:
            name: micro-vue-front-nginx-config
        - name: app-vue-front-storage
          persistentVolumeClaim:
            claimName: app-vue-front-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: micro-vue-front-service
  namespace: crolord
spec:
  selector:
    app: micro-vue-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-vue-front-nginx-config
  namespace: crolord
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;
      location / {
        try_files $uri $uri/ /index.html;
      }
      location = /healthz {
        return 200 'ok';
        access_log off;
      }
    }