apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-go-login
  namespace: crolord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-go-login
  template:
    metadata:
      labels:
        app: micro-go-login
        aliyun.com/app-language: golang
        msePilotAutoEnable: "on"
        mseNamespace: crolord
        msePilotCreateAppName: "micro-go-login"
    spec:
      containers:
        - name: micro-go-login
          image: registry.cn-hongkong.aliyuncs.com/crolord_acr_personal/microservice_code_go:micro_loginv1
          ports:
            - containerPort: 8083
          env:
            - name: ENV_FILE
              value: "/app/.env.production"
          volumeMounts:
            - name: app-log
              mountPath: /app/log
      volumes:
        - name: app-log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: micro-go-login
  namespace: crolord
spec:
  selector:
    app: micro-go-login
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP

