apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.yml: |
    # traefik.yml

    global:
      checkNewVersion: true
      sendAnonymousUsage: false

    entryPoints:
      web:
        address: ":80"

    api:
      insecure: true
      dashboard: true

    providers:
      file:
        filename: /etc/traefik/dynamic.yml
        watch: true

    log:
      level: INFO
  dynamic.yml: |
    # dynamic.yml

    http:
      routers:
        login:
          entryPoints:
            - web
          rule: "Path(`/login`)"
          service: login-service
        game:
          entryPoints:
            - web
          rule: "PathPrefix(`/game`)"
          service: game-service
        scoreboard:
          entryPoints:
            - web
          rule: "PathPrefix(`/scoreboard`)"
          service: scoreboard-service

      services:
        login-service:
          loadBalancer:
            servers:
              - url: "http://localhost:8083"
            healthCheck:
              path: "/healthz"
              interval: "30s"
              timeout: "5s"
        game-service:
          loadBalancer:
            servers:
              - url: "http://localhost:8084"
            healthCheck:
              path: "/healthz"
              interval: "30s"
              timeout: "5s"
        scoreboard-service:
          loadBalancer:
            servers:
              - url: "http://localhost:8085"
            healthCheck:
              path: "/healthz"
              interval: "30s"
              timeout: "5s"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: traefik:v2.9.10
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/traefik
      volumes:
        - name: config
          configMap:
            name: traefik-config
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
