# traefik.yml

global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"

api:
  insecure: true
  dashboard: true

providers:
  file:
    filename: ./dynamic.yml
    watch: true

log:
  level: INFO
