// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: bridge/v1/bridge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_bridge_v1_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *ActionRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ActionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionReply) Reset() {
	*x = ActionReply{}
	mi := &file_bridge_v1_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionReply) ProtoMessage() {}

func (x *ActionReply) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionReply.ProtoReflect.Descriptor instead.
func (*ActionReply) Descriptor() ([]byte, []int) {
	return file_bridge_v1_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *ActionReply) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ActionReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ActionReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_bridge_v1_bridge_proto protoreflect.FileDescriptor

const file_bridge_v1_bridge_proto_rawDesc = "" +
	"\n" +
	"\x16bridge/v1/bridge.proto\x12\tbridge.v1\"\\\n" +
	"\rActionRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"T\n" +
	"\vActionReply\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result2\xd4\x01\n" +
	"\n" +
	"JavaBridge\x12@\n" +
	"\fValidateUser\x12\x18.bridge.v1.ActionRequest\x1a\x16.bridge.v1.ActionReply\x12D\n" +
	"\x10ReserveInventory\x12\x18.bridge.v1.ActionRequest\x1a\x16.bridge.v1.ActionReply\x12>\n" +
	"\n" +
	"AuditOrder\x12\x18.bridge.v1.ActionRequest\x1a\x16.bridge.v1.ActionReply2\xd1\x01\n" +
	"\bGoBridge\x12B\n" +
	"\x0eProcessPayment\x12\x18.bridge.v1.ActionRequest\x1a\x16.bridge.v1.ActionReply\x12?\n" +
	"\vIssueRefund\x12\x18.bridge.v1.ActionRequest\x1a\x16.bridge.v1.ActionReply\x12@\n" +
	"\fQueryPayment\x12\x18.bridge.v1.ActionRequest\x1a\x16.bridge.v1.ActionReplyBG\n" +
	"\x15com.example.bridge.v1B\vBridgeProtoP\x01Z\x1farmslogcollect/go-service/pb;pbb\x06proto3"

var (
	file_bridge_v1_bridge_proto_rawDescOnce sync.Once
	file_bridge_v1_bridge_proto_rawDescData []byte
)

func file_bridge_v1_bridge_proto_rawDescGZIP() []byte {
	file_bridge_v1_bridge_proto_rawDescOnce.Do(func() {
		file_bridge_v1_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_v1_bridge_proto_rawDesc), len(file_bridge_v1_bridge_proto_rawDesc)))
	})
	return file_bridge_v1_bridge_proto_rawDescData
}

var file_bridge_v1_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bridge_v1_bridge_proto_goTypes = []any{
	(*ActionRequest)(nil), // 0: bridge.v1.ActionRequest
	(*ActionReply)(nil),   // 1: bridge.v1.ActionReply
}
var file_bridge_v1_bridge_proto_depIdxs = []int32{
	0, // 0: bridge.v1.JavaBridge.ValidateUser:input_type -> bridge.v1.ActionRequest
	0, // 1: bridge.v1.JavaBridge.ReserveInventory:input_type -> bridge.v1.ActionRequest
	0, // 2: bridge.v1.JavaBridge.AuditOrder:input_type -> bridge.v1.ActionRequest
	0, // 3: bridge.v1.GoBridge.ProcessPayment:input_type -> bridge.v1.ActionRequest
	0, // 4: bridge.v1.GoBridge.IssueRefund:input_type -> bridge.v1.ActionRequest
	0, // 5: bridge.v1.GoBridge.QueryPayment:input_type -> bridge.v1.ActionRequest
	1, // 6: bridge.v1.JavaBridge.ValidateUser:output_type -> bridge.v1.ActionReply
	1, // 7: bridge.v1.JavaBridge.ReserveInventory:output_type -> bridge.v1.ActionReply
	1, // 8: bridge.v1.JavaBridge.AuditOrder:output_type -> bridge.v1.ActionReply
	1, // 9: bridge.v1.GoBridge.ProcessPayment:output_type -> bridge.v1.ActionReply
	1, // 10: bridge.v1.GoBridge.IssueRefund:output_type -> bridge.v1.ActionReply
	1, // 11: bridge.v1.GoBridge.QueryPayment:output_type -> bridge.v1.ActionReply
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bridge_v1_bridge_proto_init() }
func file_bridge_v1_bridge_proto_init() {
	if File_bridge_v1_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_v1_bridge_proto_rawDesc), len(file_bridge_v1_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_bridge_v1_bridge_proto_goTypes,
		DependencyIndexes: file_bridge_v1_bridge_proto_depIdxs,
		MessageInfos:      file_bridge_v1_bridge_proto_msgTypes,
	}.Build()
	File_bridge_v1_bridge_proto = out.File
	file_bridge_v1_bridge_proto_goTypes = nil
	file_bridge_v1_bridge_proto_depIdxs = nil
}
